import{a as P,S as v,i as c}from"./assets/vendor-K03DOpbq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="53379882-a6be3555cf830bf3c42a42fe5",B="https://pixabay.com/api/";async function d(r,t=1){const s={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await P.get(B,{params:s})).data}catch(a){throw console.error("Error fetching images:",a),a}}const f=document.querySelector("#gallery"),y=document.querySelector("#loader"),p=document.querySelector("#load-more");let u=null;function m(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:q,downloads:_})=>`
        <li class="gallery__item">
            <a class="gallery__link" href="${a}">
                <img class="gallery__image" src="${s}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b><br>${o}</p>
                <p class="info-item"><b>Views</b><br>${i}</p>
                <p class="info-item"><b>Comments</b><br>${q}</p>
                <p class="info-item"><b>Downloads</b><br>${_}</p>
            </div>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){f.innerHTML=""}function g(){y.style.display="block"}function h(){y.style.display="none"}function b(){p.style.display="block"}function L(){p.style.display="none"}const $=document.querySelector("#search-form"),O=document.querySelector("#load-more");let l="",n=1;const w=15;$.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements.query.value.trim(),!l){c.warning({title:"Caution",message:"Please enter a search query",position:"topRight"});return}n=1,M(),L(),g();try{const t=await d(l,n);t.hits.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(m(t.hits),t.totalHits>w&&b())}catch{S()}finally{h()}});O.addEventListener("click",async()=>{n+=1,L(),g();try{const r=await d(l,n);m(r.hits),R();const t=Math.ceil(r.totalHits/w);n<t?b():c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{S()}finally{h()}});function S(){c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}function R(){const r=document.querySelector(".gallery__item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
