import{a as q,S as P,i as c}from"./assets/vendor-K03DOpbq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const B="53379882-a6be3555cf830bf3c42a42fe5",E="https://pixabay.com/api/";async function d(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(E,{params:s})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more");let u=null;function g(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:a,comments:S,downloads:_})=>`
        <li class="gallery__item">
            <a class="gallery__link" href="${i}">
                <img class="gallery__image" src="${s}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b><br>${o}</p>
                <p class="info-item"><b>Views</b><br>${a}</p>
                <p class="info-item"><b>Comments</b><br>${S}</p>
                <p class="info-item"><b>Downloads</b><br>${_}</p>
            </div>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new P(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){f.innerHTML=""}function y(){m.classList.add("is-visible")}function h(){m.classList.remove("is-visible")}function b(){p.classList.add("is-visible")}function L(){p.classList.remove("is-visible")}const $=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",n=1;const v=15;$.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){c.warning({title:"Caution",message:"Please enter a search query",position:"topRight"});return}n=1,M(),L(),y();try{const t=await d(l,n);t.hits.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(g(t.hits),t.totalHits>v&&b())}catch{w()}finally{h()}});O.addEventListener("click",async()=>{n+=1,L(),y();try{const r=await d(l,n);g(r.hits),R();const t=Math.ceil(r.totalHits/v);n<t?b():c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{w()}finally{h()}});function w(){c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}function R(){const r=document.querySelector(".gallery__item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
