import{a as q,S as P,i as s}from"./assets/vendor-K03DOpbq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const B="53379882-a6be3555cf830bf3c42a42fe5",E="https://pixabay.com/api/";async function d(r,t=1){const i={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(E,{params:i})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let u=null;function p(r){const t=r.map(({webformatURL:i,largeImageURL:a,tags:e,likes:o,views:n,comments:S,downloads:_})=>`
        <li class="gallery__item">
            <a class="gallery__link" href="${a}">
                <img class="gallery__image" src="${i}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b><br>${o}</p>
                <p class="info-item"><b>Views</b><br>${n}</p>
                <p class="info-item"><b>Comments</b><br>${S}</p>
                <p class="info-item"><b>Downloads</b><br>${_}</p>
            </div>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new P(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){f.innerHTML=""}function g(){m.classList.add("is-visible")}function y(){m.classList.remove("is-visible")}function b(){h.classList.add("is-visible")}function L(){h.classList.remove("is-visible")}const R=document.querySelector(".form"),$=document.querySelector(".load-more");let c="",l=1;const v=15;R.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.currentTarget.elements["search-text"].value.trim(),!c){s.warning({title:"Caution",message:"Please enter a search query",position:"topRight"});return}l=1,M(),L(),g();try{const t=await d(c,l);t.hits.length===0?s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(p(t.hits),t.totalHits<=v?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b())}catch{w()}finally{y()}});$.addEventListener("click",async()=>{l+=1,L(),g();try{const r=await d(c,l);if(r.hits.length===0){s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}p(r.hits),O();const t=Math.ceil(r.totalHits/v);l<t?b():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{w()}finally{y()}});function w(){s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}function O(){const r=document.querySelector(".gallery__item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
